import { Router } from 'express';
import express from 'express';
import db from '../db.js';
import { processPunchLine } from '../utils/biometricPunch.js';

// Real fingerprint/face terminals (eSSL and other ADMS/iClock-compatible devices)
// connect directly without JWT. Only registered device serial numbers are accepted.
const router = Router();

router.use(express.text({ type: '*/*' }));

function knownDevice(serial) {
  if (!serial) return null;

  return db
    .prepare(
      "SELECT * FROM biometric_devices WHERE serial_number = ? AND status = 'Active'"
    )
    .get(serial);
}

function touch(deviceId) {
  db.prepare(
    "UPDATE biometric_devices SET last_seen_at = datetime('now') WHERE id = ?"
  ).run(deviceId);
}

/*
 * Initial handshake.
 *
 * IMPORTANT:
 * We advertise realtime ATTLOG uploads but DO NOT modify
 * the terminal's date/time.
 */
router.get('/cdata', (req, res) => {
  const device = knownDevice(req.query.SN);

  if (!device) {
    return res
      .status(403)
      .type('text/plain')
      .send('Unregistered device serial number');
  }

  touch(device.id);

  const response = [
    `GET OPTION FROM: ${device.serial_number}`,
    'STAMP=0',
    'ATTLOGSTAMP=0',
    'OPERLOGStamp=0',
    'ATTPHOTOStamp=0',
    'ErrorDelay=30',
    'Delay=10',
    'TransTimes=00:00;23:59',
    'TransInterval=1',
    'TransFlag=TransData AttLog',
    'TimeZone=5.5',
    'Realtime=1',
    'Encrypt=None',
    ''
  ].join('\r\n');

  return res
    .status(200)
    .set('Content-Type', 'text/plain')
    .set('Connection', 'close')
    .send(response);
});

/*
 * Device heartbeat / command polling.
 *
 * IMPORTANT:
 * NEVER send:
 *
 *
 * The biometric terminal's own clock must remain untouched.
 *
 * The device will periodically call:
 *
 * /iclock/getrequest.aspx?SN=...
 *
 * We simply acknowledge the request with OK.
 */
router.get('/getrequest', (req, res) => {
  const device = knownDevice(req.query.SN);

  if (!device) {
    return res
      .status(403)
      .type('text/plain')
      .send('Unregistered device serial number');
  }

  touch(device.id);

  return res
    .status(200)
    .type('text/plain')
    .send('OK');
});

/*
 * Device acknowledges execution of commands.
 *
 * We do not use this endpoint to perform any time synchronization.
 */
router.post('/devicecmd', (req, res) => {
  const device = knownDevice(req.query.SN);

  if (!device) {
    return res
      .status(403)
      .type('text/plain')
      .send('Unregistered device serial number');
  }

  touch(device.id);

  return res
    .status(200)
    .type('text/plain')
    .send('OK');
});

/*
 * Some firmware requests server time via /rtdata.
 *
 * IMPORTANT:
 *
 * Returning:
 *
 *
 * causes the terminal to update its internal clock.
 *
 * We therefore only acknowledge the request.
 */
router.get('/rtdata', (req, res) => {
  const device = knownDevice(req.query.SN);

  if (!device) {
    return res
      .status(403)
      .type('text/plain')
      .send('Unregistered device serial number');
  }

  touch(device.id);

  return res
    .status(200)
    .type('text/plain')
    .send('OK');
});

/*
 * Real attendance push.
 *
 * Example body:
 *
 * TL495    2026-09-01 11:36:01    0    1    0    0    0
 *
 * The timestamp in ATTLOG is the timestamp generated by
 * the biometric terminal itself.
 */
router.post('/cdata', (req, res) => {
  const device = knownDevice(req.query.SN);

  if (!device) {
    return res
      .status(403)
      .type('text/plain')
      .send('Unregistered device serial number');
  }

  touch(device.id);

  const table = String(req.query.table || '').toUpperCase();

  // Ignore OPLOG and other non-attendance tables.
  if (table !== 'ATTLOG') {
    return res
      .status(200)
      .type('text/plain')
      .send('OK');
  }

  const body = typeof req.body === 'string' ? req.body : '';

  // Temporary/debug logging of raw attendance data.
  console.log('\n========== RAW ATTLOG ==========');
  console.log('Server time:', new Date().toString());
  console.log('SN:', device.serial_number);
  console.log('Query:', req.query);
  console.log('Body:\n' + body);
  console.log('===============================\n');

  const lines = body
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);

  let processed = 0;

  for (const line of lines) {
    const punchId = processPunchLine(device.serial_number, line);

    if (punchId !== null) {
      processed++;
    }
  }

  return res
    .status(200)
    .type('text/plain')
    .send(`OK:${processed}`);
});

export default router;